sudo: false
language: python
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
python:
    - "2.7"
install:
    - conda create --yes -q -n pyenv python=2.7 --file conda-requirements.txt
    - source activate pyenv
    - pip install -r requirements.txt
env: FLAGS=floatX=float64
script: py.test
